//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	Generated class modified by Ahmed Rashad to make properties non static (to be bindable).
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 10/05/2015 18:12:51
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace ExploreFlickr.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Resources
    {
        
        private ResourceLoader resourceLoader;
        
        public Resources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName)|| Windows.ApplicationModel.DesignMode.DesignModeEnabled)
            {
                resourceLoader = ResourceLoader.GetForViewIndependentUse("Resources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForViewIndependentUse(currentAssemblyName + "/Resources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Some error happened, please try again later."
        /// </summary>
        public virtual string ClientSideError
        {
            get
            {
                return resourceLoader.GetString("ClientSideError");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Error Happened while connecting, try again later."
        /// </summary>
        public virtual string ErrorConnecting
        {
            get
            {
                return resourceLoader.GetString("ErrorConnecting");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Loading"
        /// </summary>
        public virtual string Loading
        {
            get
            {
                return resourceLoader.GetString("Loading");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "There is no available data at the moment."
        /// </summary>
        public virtual string NoData
        {
            get
            {
                return resourceLoader.GetString("NoData");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No Internet"
        /// </summary>
        public virtual string NoInternet
        {
            get
            {
                return resourceLoader.GetString("NoInternet");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sucess"
        /// </summary>
        public virtual string Success
        {
            get
            {
                return resourceLoader.GetString("Success");
            }
        }
        
        public virtual string GetString(string name)
        {
            return resourceLoader.GetString(name);
        }
    }
}
